id: 1
name: first world
birthday: 2025-08-06T23:25:52.323119155+09:00
areas:
    - id: 1
      name: Stone Imperial Russian Stout
      population: 0
      residents: []
persons:
    - id: 1
      name: Vince Champlin
      birthday: 2025-08-06T23:25:53.327520227+09:00
      gender:
        id: 0
        name: ""
      mainrace:
        id: 0
        name: ""
      subrace: []
      mainjob:
        id: 0
        name: ""
      subjob: []
genders:
    - id: 1
      name: male
races:
    - id: 1
      name: Gainsboroalpaca
jobs:
    - id: 1
      name: SupervisorRaisin oat cookies
